Repository SfietKonstantin/pretend, pull requests merged in 2021-06, with the labels that each got.

#16 awc support
  Cargo.lock
  Cargo.toml
  pretend-awc/Cargo.toml
  pretend-awc/README.md
  pretend-awc/src/lib.rs
  pretend/Cargo.toml
  pretend/src/lib.rs
  pretend/tests/test_clients.rs
Labels: feature

#21 remove Cargo.lock and add Cargo.lock in .gitignore
  .gitignore
  Cargo.lock
  pretend-isahc/Cargo.toml
Labels: bug

#28 Derive some useful traits
  pretend-isahc/src/lib.rs
  pretend-reqwest/src/blocking.rs
  pretend-reqwest/src/lib.rs
  pretend/src/lib.rs
  pretend/src/resolver.rs
Labels: enhancement
